### ISSUE TITLE
Solve Exercism.io Exercises Using Functional Languages

### ISSUE THREAD

**Issue by anabastos** [lambda-study-group/exercism#8]
We are solving functional programming exercises together, you can help us by sending some exercises from [exercism.io](http://exercism.io) in any of theses languages:
- Clojure
- Elixir
- Elm
- Haskell
- Scala
- Lisp
- Erlang
- Purescript
- F# 
- Scheme.

Also, you can join our study group: https://t.me/joinchat/CW_t_UBMQLKQ1sEcnQHRxg
Happy Hacking! :tada: :jack_o_lantern: :ghost:

**Comment by jcorrado** [comment]
Hello!  I just opened PR #9 with the first five Clojure solutions.  I have about 10 more if you would like.  I will update them from Clojure 1.8.0 -> 1.9.0, and verify against any new exercism.io test suites.

I'm sorry for my English; I do not speak Spanish.

**Comment by anabastos** [comment]
@jcorrado Hello! All of your solutions are welcome! 

Sorry! We forgot to translate the README.md to english 😿

**Comment by jcorrado** [comment]
PR #10 with the next five exercises.  Obrigado!

**Comment by jcorrado** [comment]
PR #11 with the last five that I have, so far.  Enjoy!

**Comment by mattkimmel** [comment]
Hello! I just opened PR #13 with Scala solutions to Difference of Squares, Leap, Pangram, and Space Age.

**Comment by fswalker** [comment]
Hello! Do you also accept Racket solutions?

**Comment by appositum** [comment]
@fswalker sure!

**Comment by miguelcarvalho13** [comment]
@anabastos 
Added https://github.com/lambda-study-group/exercism/pull/19 and https://github.com/lambda-study-group/exercism/pull/18 with some `Elm` solutions.

**Comment by ramortegui** [comment]
Added https://github.com/lambda-study-group/exercism/pull/28 with Elixir solution.
